var data = ["account", "achiever", "acoustics", "act", "action", "activity", "actor", "addition", "adjustment", "advertisement", "advice", "aftermath", "afternoon", "afterthought", "agreement", "air", "airplane", "airport", "alarm", "amount", "amusement", "anger", "angle", "animal ", "answer", "ant", "ants ", "apparatus", "apparel", "apple", "apples ", "appliance", "approval", "arch", "argument", "arithmetic", "arm", "army", "art", "attack", "attempt", "attention", "attraction", "aunt", "authority", "babies ", "baby ", "back", "badge", "bag", "bait", "balance", "ball", "balloon", "balls ", "banana", "band", "base", "baseball", "basin", "basket", "basketball", "bat", "bath", "battle", "bead", "beam", "bean", "bear", "bears ", "beast", "bed", "bedroom", "beds ", "bee", "beef", "beetle", "beggar", "beginner", "behavior", "belief", "believe", "bell", "bells ", "berry", "bike", "bikes ", "bird", "birds ", "birth", "birthday", "bit", "bite", "blade", "blood", "blow", "board", "boat", "boats ", "body", "bomb", "bone", "book", "books ", "boot", "border", "bottle", "boundary", "box", "boy", "boys ", "brain", "brake", "branch", "brass", "bread", "breakfast", "breath", "brick", "bridge", "brother", "brothers ", "brush", "bubble", "bucket", "building", "bulb", "bun", "burn", "burst", "bushes", "business", "butter", "button", "cabbage", "cable", "cactus", "cake", "cakes ", "calculator", "calendar", "camera", "camp", "can", "cannon", "canvas", "cap", "caption", "car ", "card", "care", "carpenter", "carriage", "cars ", "cart", "cast", "cat", "cats ", "cattle", "cause", "cave", "celery", "cellar", "cemetery", "cent", "chain", "chair ", "chairs ", "chalk", "chance", "change", "channel", "cheese", "cherries", "cherry", "chess", "chicken ", "chickens ", "children", "chin", "church", "circle", "clam", "class", "clock", "clocks ", "cloth", "cloud", "clouds ", "clover", "club", "coach", "coal", "coast", "coat", "cobweb", "coil", "collar", "color", "comb", "comfort", "committee", "company", "comparison", "competition", "condition", "connection", "control", "cook", "copper", "copy", "cord", "cork", "corn ", "cough", "country", "cover", "cow", "cows ", "crack", "cracker", "crate", "crayon", "cream", "creator", "creature", "credit", "crib", "crime", "crook", "crow", "crowd", "crown", "crush", "cry", "cub", "cup", "current", "curtain", "curve", "cushion", "dad", "daughter", "day", "death", "debt", "decision", "deer", "degree", "design", "desire", "desk", "destruction", "detail", "development", "digestion", "dime", "dinner", "dinosaurs ", "direction", "dirt", "discovery", "discussion", "disease", "disgust", "distance", "distribution", "division", "dock", "doctor", "dog", "dogs ", "doll", "dolls ", "donkey", "door", "downtown", "drain", "drawer", "dress", "drink", "driving", "drop", "drug", "drum", "duck ", "ducks ", "dust", "ear", "earth", "earthquake", "edge", "education", "effect", "egg", "eggnog", "eggs ", "elbow", "end", "engine", "error", "event", "example", "exchange", "existence", "expansion", "experience", "expert", "eye", "eyes", "face", "fact", "fairies ", "fall", "family", "fan", "fang ", "farm", "farmer ", "father", "father", "faucet", "fear", "feast", "feather", "feeling", "feet", "fiction", "field", "fifth", "fight", "finger", "finger", "fire ", "fireman", "fish", "flag", "flame", "flavor", "flesh", "flight", "flock", "floor", "flower", "flowers ", "fly", "fog", "fold", "food", "foot", "force", "fork", "form", "fowl", "frame", "friction", "friend", "friends ", "frog", "frogs ", "front", "fruit", "fuel", "furniture", "alley", "game", "garden", "gate", "geese", "ghost", "giants ", "giraffe", "girl", "girls ", "glass", "glove", "glue", "goat", "gold", "goldfish", "good-bye ", "goose", "government", "governor", "grade", "grain", "grandfather", "grandmother", "grape", "grass", "grip", "ground", "group", "growth", "guide", "guitar", "gun", "hair", "haircut", "hall", "hammer", "hand", "hands ", "harbor", "harmony", "hat", "hate", "head", "health", "hearing", "heart", "heat", "help", "hen", "hill ", "history", "hobbies", "hole", "holiday", "home ", "honey", "hook", "hope", "horn", "horse", "horses ", "hose", "hospital", "hot", "hour", "house", "houses ", "humor", "hydrant", "ice", "icicle", "idea", "impulse", "income", "increase", "industry", "ink", "insect", "instrument", "insurance", "interest", "invention", "iron", "island", "jail", "jam", "jar", "jeans", "jelly", "jellyfish", "jewel", "join", "joke", "journey", "judge", "juice", "jump", "kettle", "key", "kick", "kiss", "kite", "kitten", "kittens ", "kitty ", "knee", "knife", "knot", "knowledge", "laborer", "lace", "ladybug", "lake", "lamp", "land", "language", "laugh", "lawyer", "lead", "leaf", "learning", "leather", "leg ", "legs", "letter", "letters ", "lettuce", "level", "library", "lift", "light", "limit", "line", "linen", "lip", "liquid", "list", "lizards ", "loaf", "lock", "locket", "look", "loss", "love", "low", "lumber", "lunch", "lunchroom", "machine", "magic", "maid", "mailbox", "man", "manager", "map", "marble", "mark", "market", "mask", "mass", "match", "meal", "measure", "meat", "meeting", "memory", "men", "metal", "mice ", "middle", "milk", "mind", "mine", "minister", "mint", "minute", "mist", "mitten", "mom", "money", "monkey", "month", "moon", "morning", "mother", "motion", "mountain", "mouth", "move", "muscle", "music", "nail", "name", "nation", "neck", "need", "needle", "nerve", "nest ", "net", "news", "night", "noise", "north", "nose", "note", "notebook", "number", "nut", "oatmeal", "observation", "ocean", "offer", "office", "oil", "operation", "opinion", "orange", "oranges ", "order", "organization", "ornament", "oven", "owl", "owner", "page", "pail", "pain", "paint", "pan", "pancake", "paper", "parcel", "parent", "park", "part", "partner", "party", "passenger", "paste", "patch", "payment", "peace", "pear", "pen", "pencil", "person", "pest", "pet", "pets ", "pickle", "picture", "pie", "pies ", "pig", "pigs ", "pin", "pipe", "pizzas ", "place", "plane", "planes ", "plant", "plantation", "plants ", "plastic", "plate", "play", "playground", "pleasure", "plot", "plough", "pocket", "point", "poison", "police", "polish", "pollution", "popcorn", "porter", "position", "pot", "potato", "powder", "power", "price", "print", "prison", "process", "produce", "profit", "property", "prose", "protest", "pull", "pump", "punishment", "purpose", "push", "quarter", "quartz", "queen", "question", "quicksand", "quiet", "quill", "quilt", "quince", "quiver", "rabbit ", "rabbits ", "rail", "railway", "rain", "rainstorm", "rake", "range", "rat", "rate", "ray", "reaction", "reading", "reason", "receipt", "recess", "record", "regret", "relation", "religion", "representative", "request", "respect", "rest", "reward", "rhythm", "rice", "riddle", "rifle", "ring", "rings ", "river", "road", "robin ", "rock", "rod", "roll", "roof", "room", "root", "rose", "route", "rub", "rule", "run", "sack", "sail", "salt", "sand", "scale", "scarecrow", "scarf", "scene", "scent", "school", "science", "scissors", "screw", "sea", "seashore", "seat", "secretary", "seed", "selection", "self", "sense", "servant", "shade", "shake", "shame", "shape", "sheep", "sheet", "shelf", "ship", "shirt", "shock", "shoe", "shoes ", "shop", "show", "side", "sidewalk", "sign", "silk", "silver", "sink", "sister", "sisters ", "size", "skate", "skin", "skirt", "sky", "slave", "sleep", "sleet", "slip", "slope", "smash", "smell", "smile", "smoke", "snail", "snails ", "snake", "snakes ", "sneeze", "snow", "soap", "society", "sock", "soda", "sofa", "son", "song", "songs ", "sort", "sound", "soup", "space", "spade", "spark", "spiders ", "sponge", "spoon", "spot", "spring", "spy", "square", "squirrel", "stage", "stamp", "star", "start", "statement", "station", "steam", "steel", "stem", "step", "stew", "stick", "sticks ", "stitch", "stocking", "stomach", "stone", "stop", "store", "story", "stove", "stranger", "straw", "stream", "street", "stretch", "string", "structure", "substance", "sugar", "suggestion", "suit", "summer", "sun", "support", "surprise", "sweater", "swim", "swing", "system", "table", "tail", "talk", "tank", "taste", "tax", "teaching", "team", "teeth ", "temper", "tendency", "tent", "territory", "test", "texture", "theory", "thing", "things ", "thought", "thread", "thrill", "throat", "throne", "thumb", "thunder", "ticket", "tiger", "time", "tin", "title", "toad", "toe", "toes", "tomatoes ", "tongue", "tooth", "toothbrush", "toothpaste", "top ", "touch", "town", "toy ", "toys ", "trade", "trail", "train", "trains ", "tramp", "transport", "tray", "treatment", "tree", "trees ", "trick", "trip", "trouble", "trousers", "truck", "trucks ", "tub", "turkey", "turn", "twig", "twist", "umbrella", "uncle", "underwear", "unit", "use", "vacation", "value", "van", "vase", "vegetable", "veil", "vein", "verse", "vessel", "vest", "view", "visitor", "voice", "volcano", "volleyball", "voyage", "walk", "wall", "war", "wash", "waste", "watch", "water", "wave", "waves ", "wax", "way", "wealth", "weather", "week", "weight", "wheel", "whip", "whistle", "wilderness", "wind ", "window ", "wine", "wing", "winter", "wire", "wish", "woman", "women", "wood", "wool", "word", "work", "worm", "wound", "wren", "wrench", "wrist", "writer", "writing", "yak", "yam", "yard", "yarn", "year", "yoke", "zebra ", "zephyr", "zinc", "zipper", "zoo"];
var movieData = ["The Shawshank Redemption",
	"The Godfather",
	"The Godfather, Part II",
	"The Dark Knight",
	"Pulp Fiction",
	"The Good, The Bad and The Ugly",
	"12 Angry Men",
	"Schindler's List",
	"The Lord of the Rings: The Return of the King",
	"Fight Club",
	"The Fellowship Of The Ring",
	"Star Wars: Episode V - The Empire Strikes Back",
	"Inception",
	"Forrest Gump",
	"One Flew Over the Cuckoo's Nest",
	"The Lord of the Rings: The Two Towers",
	"Interstellar",
	"Goodfellas",
	"The Matrix",
	"Star Wars: Episode IV - A New Hope",
	"Seven Samurai",
	"City of God",
	"Se7en",
	"The Usual Suspects",
	"The Silence of the Lambs",
	"It's a Wonderful Life",
	"Once Upon a Time in the West",
	"Leon: The Professional",
	"Life Is Beautiful",
	"Casablanca",
	"Raiders of the Lost Ark",
	"American History X",
	"Saving Private Ryan",
	"City Lights",
	"Psycho",
	"Spirited Away",
	"Rear Window",
	"Intouchables",
	"Modern Times",
	"Whiplash",
	"Terminator 2: Judgment Day",
	"Memento",
	"The Green Mile",
	"The Pianist",
	"The Departed",
	"Sunset Boulevard",
	"Apocalypse Now",
	"Dr. Strangelove or How I Learned to Stop Worrying and Love the Bomb",
	"Gladiator",
	"Back to the Future",
	"Alien",
	"The Prestige",
	"The Great Dictator",
	"The Lives of Others",
	"The Lion King",
	"Django Unchained",
	"The Dark Knight Rises",
	"Cinema Paradiso",
	"The Shining",
	"Paths of Glory",
	"American Beauty",
	"Wall-E",
	"North by Northwest",
	"Aliens",
	"Citizen Kane",
	"Vertigo",
	"Amelie",
	"M",
	"Das Boot",
	"Grave of the Fireflies",
	"Toy Story 3",
	"Oldboy",
	"Princess Mononoke",
	"Star Wars: Episode VI - Return of the Jedi",
	"Once Upon a Time in America",
	"A Clockwork Orange",
	"Reservoir Dogs",
	"Taxi Driver",
	"Double Indemnity",
	"Braveheart",
	"Requiem for a Dream",
	"To Kill a Mockingbird",
	"Lawrence of Arabia",
	"Witness for the Prosecution",
	"Eternal Sunshine of the Spotless Mind",
	"Full Metal Jacket",
	"Singin' in the Rain",
	"The Sting",
	"Bicycle Thieves",
	"Amadeus",
	"Monty Python and the Holy Grail",
	"Snatch",
	"Rashomon",
	"L.A. Confidential",
	"For a Few Dollars More",
	"2001: A Space Odyssey",
	"The Kid",
	"All About Eve",
	"The Apartment",
	"Some Like It Hot",
	"Inglourious Basterds",
	"Birdman",
	"Indiana Jones and the Last Crusade",
	"The Treasure of the Sierra Madre",
	"The Third Man",
	"A Seperation",
	"Yojimbo",
	"Toy Story",
	"Batman Begins",
	"Metropolis",
	"Like Stars on Earth",
	"Unforgiven",
	"Scarface",
	"Raging Bull",
	"Up",
	"Chinatown",
	"3 Idiots",
	"The Great Escape",
	"Downfall",
	"Boyhood",
	"Die Hard",
	"On the Waterfront",
	"Pan's Labyrinth",
	"Mr. Smith Goes to Washington",
	"The Hunt",
	"Heat",
	"CM101MMXI Fundamentals",
	"Gone Girl",
	"The Bridge on the River Kwai",
	"Good Will Hunting",
	"The Bandit",
	"My Neighbor Totoro",
	"The Seventh Seal",
	"Ikiru",
	"The Gold Rush",
	"The Elephant Man",
	"The Wolf of Wall Street",
	"Ran",
	"Wild Strawberries",
	"Blade Runner",
	"The General",
	"Lock, Stock and Two Smoking Barrels",
	"The Secret in Their Eyes",
	"Casino",
	"Gran Torino",
	"The Big Lebowski",
	"Warrior",
	"Rebecca",
	"V for Vendetta",
	"Howl's Moving Castle",
	"Paint It Yellow",
	"The Deer Hunter",
	"It Happened One Night",
	"Cool Hand Luke",
	"How to Train Your Dragon",
	"Fargo",
	"Judgment at Nuremberg",
	"Trainspotting",
	"Gone with the Wind",
	"Rush",
	"Into the Wild",
	"The Maltese Falcon",
	"A Beautiful Mind",
	"Dial M for Murder",
	"The Sixth Sense",
	"The Wages of Fear",
	"Hotel Rwanda",
	"The Thing",
	"Finding Nemo",
	"Mary and Max",
	"No Country for Old Men",
	"Butch Cassidy and the Sundance Kid",
	"Kill Bill: Vol. 1",
	"Platoon",
	"Life of Brian",
	"Incendies",
	"Guardians of the Galaxy",
	"Dil Chahta Hai",
	"12 Years a Slave",
	"Network",
	"Touch of Evil",
	"Diabolique (1955)",
	"Annie Hall",
	"The Princess Bride",
	"There Will Be Blood",
	"The Grand Budapest Hotel",
	"Stand by Me",
	"Sin City",
	"Ben-Hur",
	"The 400 Blows",
	"Amores Perros",
	"In the Name of the Father",
	"Million Dollar Baby",
	"The Grapes of Wrath",
	"The Wizard of Oz",
	"Hachi: A Dog's Tale",
	"Persona",
	"The Best Years of Our Lives",
	"The Avengers",
	"Nausicaä of the Valley of the Wind",
	"The Bourne Ultimatum",
	"Gandhi",
	"The Imitation Game",
	"Donnie Darko",
	"8 1/2",
	"Gangs of Wasseypur",
	"Strangers on a Train",
	"Infernal Affairs",
	"Stalker",
	"12 Monkeys",
	"Jaws",
	"Shutter Island",
	"X-Men: Days of Future Past",
	"High Noon",
	"Lagaan: Once Upon a Time in India",
	"Notorious",
	"The Terminator",
	"Before Sunrise",
	"The King's Speech",
	"Groundhog Day",
	"Harry Potter and the Deathly Hallows: Part 2",
	"Fanny and Alexander",
	"Ip Man",
	"The Battle of Algiers",
	"Rocky",
	"Dog Day Afternoon",
	"The Night of the Hunter",
	"Monsters, Inc.",
	"La Haine",
	"Memories of Murder",
	"La Strada",
	"Pirates of the Caribbean: The Curse of the Black Pearl",
	"Who's Afraid of Virginia Woolf?",
	"Barry Lyndon",
	"A Fistful of Dollars",
	"Castle in the Sky",
	"The Truman Show",
	"The Big Sleep",
	"The Help",
	"Jurassic Park",
	"Roman Holiday",
	"The Graduate",
	"The Hustler",
	"Papillon",
	"Beauty and the Beast",
	"In the Mood for Love",
	"The Celebration",
	"Prisoners",
	"Rope",
	"Swades: We, the People"
];

var defaultData = [
	"Africa",
	"Agent",
	"Air",
	"Alien",
	"Alps",
	"Amazon",
	"Ambulance",
	"America",
	"Angel",
	"Antarctica",
	"Apple",
	"Arm",
	"Atlantis",
	"Australia",
	"Aztec",
	"Back",
	"Ball",
	"Band",
	"Bank",
	"Bar",
	"Bark",
	"Bat",
	"Battery",
	"Beach",
	"Bear",
	"Beat",
	"Bed",
	"Beijing",
	"Bell",
	"Belt",
	"Berlin",
	"Bermuda",
	"Berry",
	"Bill",
	"Block",
	"Board",
	"Bolt",
	"Bomb",
	"Bond",
	"Boom",
	"Boot",
	"Bottle",
	"Bow",
	"Box",
	"Bridge",
	"Brush",
	"Buck",
	"Buffalo",
	"Bug",
	"Bugle",
	"Button",
	"Calf",
	"Canada",
	"Cap",
	"Capital",
	"Car",
	"Card",
	"Carrot",
	"Casino",
	"Cast",
	"Cat",
	"Cell",
	"Centaur",
	"Center",
	"Chair",
	"Change",
	"Charge",
	"Check",
	"Chest",
	"Chick",
	"China",
	"Chocolate",
	"Church",
	"Circle",
	"Cliff",
	"Cloak",
	"Club",
	"Code",
	"Cold",
	"Comic",
	"Compound",
	"Concert",
	"Conductor",
	"Contract",
	"Cook",
	"Copper",
	"Cotton",
	"Court",
	"Cover",
	"Crane",
	"Crash",
	"Cricket",
	"Cross",
	"Crown",
	"Cycle",
	"Czech",
	"Dance",
	"Date",
	"Day",
	"Death",
	"Deck",
	"Degree",
	"Diamond",
	"Dice",
	"Dinosaur",
	"Disease",
	"Doctor",
	"Dog",
	"Draft",
	"Dragon",
	"Dress",
	"Drill",
	"Drop",
	"Duck",
	"Dwarf",
	"Eagle",
	"Egypt",
	"Embassy",
	"Engine",
	"England",
	"Europe",
	"Eye",
	"Face",
	"Fair",
	"Fall",
	"Fan",
	"Fence",
	"Field",
	"Fighter",
	"Figure",
	"File",
	"Film",
	"Fire",
	"Fish",
	"Flute",
	"Fly",
	"Foot",
	"Force",
	"Forest",
	"Fork",
	"France",
	"Game",
	"Gas",
	"Genius",
	"Germany",
	"Ghost",
	"Giant",
	"Glass",
	"Glove",
	"Gold",
	"Grace",
	"Grass",
	"Greece",
	"Green",
	"Ground",
	"Ham",
	"Hand",
	"Hawk",
	"Head",
	"Heart",
	"Helicopter",
	"Himalayas",
	"Hole",
	"Hollywood",
	"Honey",
	"Hood",
	"Hook",
	"Horn",
	"Horse",
	"Horseshoe",
	"Hospital",
	"Hotel",
	"Ice",
	"Ice Cream",
	"India",
	"Iron",
	"Ivory",
	"Jack",
	"Jam",
	"Jet",
	"Jupiter",
	"Kangaroo",
	"Ketchup",
	"Key",
	"Kid",
	"King",
	"Kiwi",
	"Knife",
	"Knight",
	"Lab",
	"Lap",
	"Laser",
	"Lawyer",
	"Lead",
	"Lemon",
	"Leprechaun",
	"Life",
	"Light",
	"Limousine",
	"Line",
	"Link",
	"Lion",
	"Litter",
	"Loch Ness",
	"Lock",
	"Log",
	"London",
	"Luck",
	"Mail",
	"Mammoth",
	"Maple",
	"Marble",
	"March",
	"Mass",
	"Match",
	"Mercury",
	"Mexico",
	"Microscope",
	"Millionaire",
	"Mine",
	"Mint",
	"Missile",
	"Model",
	"Mole",
	"Moon",
	"Moscow",
	"Mount",
	"Mouse",
	"Mouth",
	"Mug",
	"Nail",
	"Needle",
	"Net",
	"New York",
	"Night",
	"Ninja",
	"Note",
	"Novel",
	"Nurse",
	"Nut",
	"Octopus",
	"Oil",
	"Olive",
	"Olympus",
	"Opera",
	"Orange",
	"Organ",
	"Palm",
	"Pan",
	"Pants",
	"Paper",
	"Parachute",
	"Park",
	"Part",
	"Pass",
	"Paste",
	"Penguin",
	"Phoenix",
	"Piano",
	"Pie",
	"Pilot",
	"Pin",
	"Pipe",
	"Pirate",
	"Pistol",
	"Pit",
	"Pitch",
	"Plane",
	"Plastic",
	"Plate",
	"Platypus",
	"Play",
	"Plot",
	"Point",
	"Poison",
	"Pole",
	"Police",
	"Pool",
	"Port",
	"Post",
	"Pound",
	"Press",
	"Princess",
	"Pumpkin",
	"Pupil",
	"Pyramid",
	"Queen",
	"Rabbit",
	"Racket",
	"Ray",
	"Revolution",
	"Ring",
	"Robin",
	"Robot",
	"Rock",
	"Rome",
	"Root",
	"Rose",
	"Roulette",
	"Round",
	"Row",
	"Ruler",
	"Satellite",
	"Saturn",
	"Scale",
	"School",
	"Scientist",
	"Scorpion",
	"Screen",
	"Scuba Diver",
	"Seal",
	"Server",
	"Shadow",
	"Shakespeare",
	"Shark",
	"Ship",
	"Shoe",
	"Shop",
	"Shot",
	"Sink",
	"Skyscraper",
	"Slip",
	"Slug",
	"Smuggler",
	"Snow",
	"Snowman",
	"Sock",
	"Soldier",
	"Soul",
	"Sound",
	"Space",
	"Spell",
	"Spider",
	"Spike",
	"Spine",
	"Spot",
	"Spring",
	"Spy",
	"Square",
	"Stadium",
	"Staff",
	"Star",
	"State",
	"Stick",
	"Stock",
	"Straw",
	"Stream",
	"Strike",
	"String",
	"Sub",
	"Suit",
	"Superhero",
	"Swing",
	"Switch",
	"Table",
	"Tablet",
	"Tag",
	"Tail",
	"Tap",
	"Teacher",
	"Telescope",
	"Temple",
	"Theater",
	"Thief",
	"Thumb",
	"Tick",
	"Tie",
	"Time",
	"Tokyo",
	"Tooth",
	"Torch",
	"Tower",
	"Track",
	"Train",
	"Triangle",
	"Trip",
	"Trunk",
	"Tube",
	"Turkey",
	"Undertaker",
	"Unicorn",
	"Vacuum",
	"Van",
	"Vet",
	"Wake",
	"Wall",
	"War",
	"Washer",
	"Washington",
	"Watch",
	"Water",
	"Wave",
	"Web",
	"Well",
	"Whale",
	"Whip",
	"Wind",
	"Witch",
	"Worm",
	"Yard"
];

var spanishData = [
	"Aguila",
	"Aguja",
	"Agujero",
	"Aire",
	"Alemania",
	"Algodun",
	"Alianza",
	"Alpes",
	"Ambulancia",
	"America",
	"Angel",
	"Anillo",
	"Antartida",
	"Antorcha",
	"Araoa",
	"Archivo",
	"Arco",
	"Argentina",
	"Articulo",
	"As",
	"Atlantida",
	"Azteca",
	"Baile",
	"Bala",
	"Ballena",
	"Banco",
	"Banda",
	"Baoo",
	"Barco",
	"Barra",
	"Bateria",
	"Berlin",
	"Bermudas",
	"Bicho",
	"Blanco",
	"Bloque",
	"Boca",
	"Bola",
	"Bolsa",
	"Bomba",
	"Bosque",
	"Bota",
	"Botella",
	"Botun",
	"Brazo",
	"Bruja",
	"Caballero",
	"Caballo",
	"Cabeza",
	"Cabina",
	"Cabo",
	"Cactus",
	"Cadena",
	"Caja",
	"Cama",
	"Camara",
	"Cambio",
	"Campana",
	"Campo",
	"Canal",
	"Canguro",
	"Canto",
	"Caoa",
	"Capa",
	"Capital",
	"Caqui",
	"Cara",
	"Caravana",
	"Carga",
	"Carrera",
	"Carro",
	"Carta",
	"Casco",
	"Casino",
	"Caza",
	"Cementerio",
	"Centauro",
	"Centro",
	"Cervantes",
	"Checo",
	"Chocolate",
	"Choque",
	"Chuleta",
	"Cientifico",
	"Cinta",
	"Cinturun",
	"Circulo",
	"Clase",
	"Coche",
	"Cocinero",
	"Coco",
	"Cudigo",
	"Cola",
	"Culera",
	"Columna",
	"Cometa",
	"Compas",
	"Concierto",
	"Conejo",
	"Contrabandista",
	"Copa",
	"Corazun",
	"Corneta",
	"Corona",
	"Corredor",
	"Corriente",
	"Corte",
	"Cresta",
	"Cromo",
	"Cruz",
	"Cuadro",
	"Cuarto",
	"Cubierta",
	"Cubo",
	"Cuchillo",
	"Cuello",
	"Cuerda",
	"Cuerno",
	"Cura",
	"Dama",
	"Delta",
	"Destino",
	"Dia",
	"Diamante",
	"Diana",
	"Diario",
	"Diente",
	"Dinosaurio",
	"Disco",
	"Don",
	"Dragun",
	"Duende",
	"Egipto",
	"Embajada",
	"Emperador",
	"Enano",
	"Enfermedad",
	"Enfermera",
	"Enlace",
	"Escorpiun",
	"Espacio",
	"Espia",
	"Estaciun",
	"Estadio",
	"Estado",
	"Estrella",
	"Estudio",
	"Etiqueta",
	"Europa",
	"Extraterrestre",
	"Falda",
	"Fantasma",
	"Faro",
	"Ficha",
	"Fiesta",
	"Figura",
	"Flauta",
	"Flecha",
	"Foso",
	"Francia",
	"Frente",
	"Fuego",
	"Fuente",
	"Fuerza",
	"Furgoneta",
	"Gancho",
	"Gato",
	"Genio",
	"Gigante",
	"Golfo",
	"Golondrina",
	"Golpe",
	"Goma",
	"Gundola",
	"Gota",
	"Grado",
	"Granada",
	"Grano",
	"Grecia",
	"Grifo",
	"Guante",
	"Guardia",
	"Guerra",
	"Gusano",
	"Helado",
	"Helicuptero",
	"Hielo",
	"Hierba",
	"Hoja",
	"Hollywood",
	"Horca",
	"Hospital",
	"Hotel",
	"Iglesia",
	"Iman",
	"India",
	"Indice",
	"Inglaterra",
	"Italia",
	"Jarra",
	"Judia",
	"Juicio",
	"Kiwi",
	"Ladrun",
	"Lago Ness",
	"Laser",
	"Latigo",
	"Lengua",
	"Leun",
	"Libra",
	"Lima",
	"Limusina",
	"Linea",
	"Lista",
	"Llama",
	"Llave",
	"Lomo",
	"Londres",
	"Luna",
	"Luz",
	"Maestro",
	"Magia",
	"Malta",
	"Mancha",
	"Mando",
	"Manga",
	"Mango",
	"Mano",
	"Manzana",
	"Maoana",
	"Marca",
	"Marcha",
	"Marfil",
	"Masa",
	"Mascara",
	"Mazo",
	"Medico",
	"Mercurio",
	"Mesa",
	"Metro",
	"Mexico",
	"Micro",
	"Microscopio",
	"Mielo",
	"Millonario",
	"Mina",
	"Misil",
	"Modelo",
	"Mudulo",
	"Monitor",
	"Mono",
	"Mortero",
	"Mosc˙",
	"Motor",
	"Muelle",
	"Muerte",
	"Muoeca",
	"Muro",
	"Naranja",
	"Nave",
	"Nieve",
	"Nilo",
	"Ninja",
	"Noche",
	"Nota",
	"Nudo",
	"Nueva York",
	"Obra",
	"Ojo",
	"Ola",
	"Olimpo",
	"Upera",
	"Orden",
	"Urgano",
	"Ornitorrinco",
	"Oro",
	"Oso",
	"Pala",
	"Palma",
	"Pantalla",
	"Papel",
	"Paracaidas",
	"Pase",
	"Paso",
	"Pasta",
	"Pastel",
	"Pavo",
	"Pekin",
	"Pelicula",
	"Pelotun",
	"Pendiente",
	"Perro",
	"Pez",
	"Pico",
	"Pie",
	"Pieza",
	"Pila",
	"Piloto",
	"Pincho",
	"Ping¸ino",
	"Pinta",
	"Pioa",
	"Piramide",
	"Pirata",
	"Pista",
	"Pistola",
	"Placa",
	"Plano",
	"Planta",
	"Platano",
	"Playa",
	"Plomo",
	"Pluma",
	"Policia",
	"Polo",
	"Portada",
	"Portero",
	"Potro",
	"Prensa",
	"Prima",
	"Princesa",
	"Puente",
	"Puerto",
	"Pulpo",
	"Pulso",
	"Punta",
	"Punto",
	"Radio",
	"Rascacielos",
	"Ratun",
	"Rayo",
	"Red",
	"Regla",
	"Reina",
	"Reserva",
	"Revoluciun",
	"Rey",
	"Robot",
	"Rojo",
	"Roma",
	"Ronda",
	"Rosa",
	"Ruleta",
	"Sable",
	"Sa"
];

englishUkrainianData = [
	"Drum - Барабан",
	"Nose - Ніс",
	"Anchor - Якір",
	"Shoulder - Плече",
	"Spirit - Дух",
	"Book - Книга",
	"Kick - Удар",
	"Boss - Бос",
	"Rope - Мотузка",
	"Avalanche - Лавина",
	"Sheet - Аркуш",
	"Tuxedo - Смокінг",
	"Shampoo - Шампунь",
	"Frog - Жаба",
	"Milk - Молоко",
	"Gangster - Гангстер",
	"Spurs - Шпори",
	"Step - Крок",
	"Mummy - Мумія",
	"Kung Fu - Кунг-фу",
	"Wedding - Весілля",
	"Minotaur - Мінотавр",
	"Sleep - Сон",
	"Eden - Едем",
	"Boxer - Боксер",
	"Homer - Гомер",
	"Peach - Персик",
	"Waitress - Офіціантка",
	"Computer - Комп'ютер",
	"Tiger - Тигр",
	"Wagon - Вагон",
	"Stamp - Штамп",
	"Flood - Повінь",
	"Manicure - Манікюр",
	"Swamp - Болото",
	"Dressing - Вбрання",
	"Radio - Радіо",
	"Banana - Банан",
	"Pad - Блокнот",
	"Sun - Сонце",
	"Sugar - Цукор",
	"Ram - Баран",
	"Sack - Мішок",
	"Rainbow - Веселка",
	"Magazine - Журнал",
	"Story - Історія",
	"Pig - Свиня",
	"Comet - Комета",
	"Chip - Чіп",
	"Bean - Боб",
	"Pop - Поп",
	"Page - Сторінка",
	"Groom - Наречений",
	"Paddle - Байдарка",
	"Mirror - Дзеркало",
	"Sword - Меч",
	"Tip - Порада",
	"Shell - Оболонка",
	"Peanut - Арахіс",
	"House - Будинок",
	"Hit - Хіт",
	"Brain - Мозок",
	"Santa - Санта",
	"Halloween - Хеллоуїн",
	"Hide - Сховище",
	"Brazil - Бразилія",
	"Cone - Конус",
	"Knot - Вузол",
	"Wish - Бажання",
	"Rust - Іржа",
	"Ace - Туз",
	"Bread - Хліб",
	"Sumo - Сумо",
	"Reindeer - Олень",
	"Tea - Чай",
	"Armor - Броня",
	"Toast - Тост",
	"Polo - Поло",
	"Laundry - Прання",
	"Bowl - Чаша",
	"Trick - Трюк",
	"Crusader - Хрестоносець",
	"Farm - Ферма",
	"Mona Lisa - Мона Ліза",
	"Beer - Пиво",
	"Alaska - Аляска",
	"Jellyfish - Медуза",
	"Medic - Медик",
	"Mustard - Гірчиця",
	"Hawaii - Гаваї",
	"Bass - Бас",
	"Tutu - Туту",
	"Barbecue - Барбекю",
	"Balloon - Повітряна куля",
	"Gear - Механізм",
	"Stable - Стайня",
	"Wheelchair - Коляска",
	"Storm - Шторм",
	"Shorts - Шорти",
	"Steel - Сталь",
	"Bucket - Відро",
	"Dash - Тире",
	"Walrus - Морж",
	"Lemonade - Лимонад",
	"Flag - Прапор",
	"Cave - Печера",
	"Ant - Мурашки",
	"Vampire - Вампір",
	"Tattoo - Тату",
	"Ranch - Ранчо",
	"Locust - Саранча",
	"Rifle - Рушниця",
	"Viking - Вікінг",
	"Blizzard - Буран",
	"Makeup - Макіяж",
	"Potter - Поттер",
	"Taste - Смак",
	"Blues - Блюз",
	"Golf - Гольф",
	"Pine - Сосна",
	"Doll - Лялька",
	"Lunch - Обід",
	"Skates - Ковзани",
	"Craft - Ремесло",
	"Pew - Стілець",
	"Pen - Ручка",
	"Butter - Масло",
	"Pillow - Подушка",
	"Castle - Замок",
	"Scroll - Прокрутка",
	"Disk - Диск",
	"Drone - Дрон",
	"Hammer - Молоток",
	"Floor - Підлога",
	"Jail - В'язниця",
	"Break - Перерва",
	"Lace - Мереживо",
	"Pocket - Кишеня",
	"Tin - Олово",
	"Flat - Квартира",
	"Cuckoo - Зозуля",
	"Hair - Волосся",
	"Mud - Бруд",
	"Jeweler - Ювелір",
	"Hercules - Геркулес",
	"Blade - Лезо",
	"Mosquito - Комаха",
	"Pea - Горох",
	"Iceland - Ісландія",
	"Frost - Мороз",
	"Coach - Тренер",
	"Potato - Картопля",
	"Snap - Хватка",
	"Cake - Торт",
	"Turtle - Черепаха",
	"Christmas - Різдво",
	"Cherry - Вишня",
	"Moses - Мойсей",
	"Team - Команда",
	"Cane - Стебло",
	"Bulb - Лампочка",
	"Biscuit - Бісквіт",
	"Spray - Спрей",
	"Pepper - Перець",
	"Puppet - Кукла",
	"Mill - Млин",
	"Maracas - Маракас",
	"Foam - Піна",
	"Memory - Пам'ять",
	"Jumper - Джемпер",
	"Comb - Гребінець",
	"Glasses - Окуляри",
	"Pizza - Піца",
	"Soap - Мило",
	"Big Ben - Біг Бен",
	"Sled - Санки",
	"Violet - Фіолетовий",
	"Bubble - Міхур",
	"Spoon - Ложка",
	"Onion - Цибуля",
	"Genie - Джин",
	"Tank - Танк",
	"Sherlock - Шерлок",
	"Bay - Затока",
	"Dryer - Сушарка",
	"Brother - Брат",
	"Mess - Безлад",
	"Ladder - Сходи",
	"Scarecrow - Опудало",
	"Notre Dame - Нотр-Дам",
	"Kilt - Кілт",
	"Shed - Сарай",
	"Bonsai - Бонсай",
	"Wonderland - Країна чудес",
	"Sling - Слінг",
	"Squirrel - Білка",
	"Hose - Шланг",
	"Marathon - Марафон",
	"Bride - Наречена",
	"King Arthur - Король Артур",
	"Cowboy - Ковбой",
	"Governor - Губернатор",
	"Cable - Кабель",
	"Razor - Бритва",
	"Fog - Туман",
	"Fever - Лихоманка",
	"Street - Вулиця",
	"Texas - Техас",
	"Napoleon - Наполеон",
	"Earth - Земля",
	"Cheese - Сир",
	"Dentist - Стоматолог",
	"Wheel - Колесо",
	"Butterfly - Метелик",
	"Zombie - Зомбі",
	"Joan of Arc - Жанна д'Арк",
	"Blacksmith - Коваль",
	"Clock - Годинник",
	"Columbus - Колумб",
	"Big Bang - Великий вибух",
	"Pentagon - Пентагон",
	"Army - Армія",
	"Rice - Рис",
	"Minute - Хвилина",
	"Dollar - Долар",
	"Shoot - Стріляти",
	"Cow - Корова",
	"Joker - Джокер",
	"Univerity - Університет",
	"Camp - Табір",
	"Mohawk - Індіанець",
	"Anthem - Гімн",
	"Einstein - Ейнштейн",
	"Brick - Цегла",
	"Crab - Краб",
	"Poland - Польща",
	"Captain - Капітан",
	"Letter - Послання",
	"Director - Директор",
	"Sister - Сестра",
	"Mountie - Вершник",
	"Whistle - Свисток",
	"Brass - Латунь",
	"Salad - Салат",
	"Cleopatra - Клеопатра",
	"Bath - Ванна",
	"Goat - Козел",
	"Lightning - Блискавка",
	"Sherwood - Шервуд",
	"Sphinx - Сфінкс",
	"River - Річка",
	"Saloon - Салон",
	"Ink - Чорнило",
	"Soup - Суп",
	"Love - Любов",
	"Lumberjack - Лісоруб",
	"Window - Вікно",
	"Collar - Комірець",
	"Ash - Зола",
	"Leaf - Лист",
	"Pitcher - Глечик",
	"Newton - Ньютон",
	"Crystal - Кристал",
	"Tear - Сльоза",
	"Skull - Череп",
	"Paint - Фарба",
	"Axe - Топор",
	"Wing - Крило",
	"Scratch - Подряпина",
	"Record - Запис",
	"Sahara - Сахара",
	"Kitchen - Кухня",
	"Helmet - Шолом",
	"Smoke - Дим",
	"Penny - Пенні",
	"Gum - Гумка",
	"Bee - Бджола",
	"Guitar - Гітара",
	"Nylon - Нейлон",
	"Volcano - Вулкан",
	"Judge - Суддя",
	"Mile - Миля",
	"Tipi - Вігвам",
	"Baby - Дитина",
	"Stethoscope - Стетоскоп",
	"Dream - Мрія",
	"Sand - Пісок",
	"Dwarf - Карлик",
	"Astronaut - Космонавт",
	"Coast - Узбережжя",
	"Leather - Шкіра",
	"Fiddle - Скрипка",
	"Kiss - Поцілунок",
	"Bikini - Бікіні",
	"Egg - Яйце",
	"Goldilocks - Жовтець",
	"Popcorn - Попкорн",
	"Ear - Вухо",
	"Caesar - Цезар",
	"Greenhouse - Теплиця",
	"Dust - Пил",
	"Slipper - Капці",
	"Troll - Троль",
	"Quack - Чорт",
	"Volume - Обсяг",
	"Ski - Лижі",
	"Russia - Росія",
	"Pearl - Перлина",
	"Pacific - Тихий океан",
	"Easter - Великдень",
	"Quarter - Квартал",
	"Microwave - Мікрохвильова піч",
	"Shower - Душ",
	"Fuel - Паливо",
	"Earthquake - Землетрус",
	"Crow - Ворона",
	"Magician - Чарівник",
	"Nerve - Нерв",
	"Thunder - Грім",
	"Musketeer - Мушкетер",
	"Glacier - Льодовик",
	"Powder - Порошок",
	"Roll - Рулон",
	"Werewolf - Перевертень",
	"Chain - Ланцюг",
	"Second - Другий",
	"Bunk - Ліжко",
	"Beard - Борода",
	"Steam - Steam",
	"Cloud - Хмара",
	"Valentine - Валентин",
	"Sticker - Наклейка",
	"Snake - Змія",
	"Battleship - Броненосець",
	"Battle - Битва",
	"Map - Карта",
	"Virus - Вірус",
	"Tornado - Торнадо",
	"Bicycle - Велосипед",
	"Parrot - Папуга",
	"Hamburger - Гамбургер",
	"Sign - Знак",
	"Noah - Ной",
	"Wizard - Чаклун",
	"Parade - Парад",
	"Apron - Фартух",
	"Curry - Каррі",
	"Beam - Пучок",
	"Desk - Стіл",
	"Saddle - Сідло",
	"Rat - Щур",
	"Bacon - Бекон",
	"Rubber - Гума",
	"Patient - Пацієнт",
	"Saw - Пила",
	"Oasis - Оазис",
	"Venus - Венера",
	"Bench - Лавка",
	"Rip - Розрив",
	"St.Patrick - Св. Патрик",
	"Road - Дорога",
	"Chalk - Крейда",
	"Gymnast - Гімнастка",
	"Meter - Метр",
	"Rodeo - Родео",
	"Silk - Шовк",
	"Coffee - Кава",
	"Jockey - Жокей",
	"Smoothie - Смузі",
	"Salsa - Сальса",
	"Sail - Вітрило",
	"Wool - Вовна",
	"Tunnel - Тунель",
	"Garden - Сад",
	"Smell - Запах",
	"Door - Двері",
	"Wood - Деревина",
	"Country - Країна",
	"Elephant - Слон",
	"Mark - Марка",
	"Blind - Сліпий",
	"Squash - Сквош",
	"Mother - Мати",
	"Drawing - Малювання",
	"Rail - Залізниця",
	"Miss - Міс",
	"Purse - Гаманець",
	"Igloo - Іглу",
	"Lip - Губа",
	"Monkey - Мавпа",
	"Bowler - Боулер",
	"Sweat - Піт",
	"Driver - Водій",
	"Delta - Дельта",
	"Salt - Сіль",
	"Sloth - Лінивець",
	"Attic - Мансарда"
];